name: Refresh .md's
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Add PR base ref
      run: |
        git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}

    - name: nbconvert README
      uses: runsascoded/nbconvert@latest
      with:
        args:
        - '-x'
        - '-f'
